### PR TITLE
[WIP] Add more benchmarks

### PR DESCRIPTION
**Pull request by utkarsh530**
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by utkarsh530** [comment]
Fitzhugh Nagamo Benchmarks:

```julia
BenchmarkTools.Trial: 28 samples with 1 evaluation.
 Range (min … max):  170.824 ms … 211.453 ms  ┊ GC (min … max): 0.00% … 11.76%
 Time  (median):     179.649 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   180.377 ms ±   9.862 ms  ┊ GC (mean ± σ):  1.84% ±  2.55%

  █                     ▁▁                                       
  █▄▆▆▁▁▁▁▁▁▁▄▁▁▄▁▁▁▁▁▁▁██▄▄▁▁▁▁▁▁▄▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄ ▁
  171 ms           Histogram: frequency by time          211 ms <

 Memory estimate: 2.06 MiB, allocs estimate: 42709.
```

```
julia> @show gsol
gsol = PSOGPU.SPSOGBest{SVector{4, Float32}, Float32}(Float32[1.4175674, 0.934993, 0.049795125, 0.5001013], 3.5554986f-5)
PSOGPU.SPSOGBest{SVector{4, Float32}, Float32}(Float32[1.4175674, 0.934993, 0.049795125, 0.5001013], 3.5554986f-5)

```

**Comment by utkarsh530** [comment]
Lotka Volterra:

```julia
julia> @benchmark PSOGPU.parameter_estim_ode!($prob, $(deepcopy(solver_cache)),
           $lb,
           $ub, Val(adaptive); saveat = t, dt = 0.1, backend = CUDABackend())
BenchmarkTools.Trial: 57 samples with 1 evaluation.
 Range (min … max):  78.997 ms … 117.178 ms  ┊ GC (min … max): 0.00% … 21.38%
 Time  (median):     80.868 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   87.706 ms ±  10.700 ms  ┊ GC (mean ± σ):  3.43% ±  4.84%

  █▃▃                                                           
  ███▆▄▃▁▁▁▃▁▁▃▁▄▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▆▇▃▃▁▃▃▃▁▃▁▃▁▃▁▁▁▁▁▁▃▁▁▁▁▁▁▃ ▁
  79 ms           Histogram: frequency by time          114 ms <

 Memory estimate: 2.13 MiB, allocs estimate: 43106.
```

```julia
julia> @time gsol = PSOGPU.parameter_estim_ode!(prob, solver_cache,
           lb,
           ub, Val(adaptive); saveat = t, dt = 0.1, maxiters = 100)
  0.079444 seconds (43.10 k allocations: 2.124 MiB)
PSOGPU.SPSOGBest{SVector{4, Float64}, Float64}([1.8749830934479235, 1.874982914866944, 2.1886256202246708, 2.18862664910988], 4.5790030071118923e-11)

```

**Comment by ChrisRackauckas** [comment]
Why not make these SciMLBenchmarks runs?

**Comment by utkarsh530** [comment]
Yeah, I plan to do it once I tag the release and populate some docs.

**Pull request merged**
